# Ansible Automation Platform 2.6 Custom Resource
# Requires: AAP operator installed in aap namespace
# Requires: nfs-csi StorageClass for Hub file storage (RWX)
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    file_storage_storage_class: nfs-csi
    file_storage_access_mode: ReadWriteMany
    file_storage_size: 10Gi
