# Wave 5: HashiCorp Vault CE (Helm)
# NOTE: After sync, Vault must be manually initialized and unsealed.
# Then run configure-vault.sh and store-secrets-in-vault.sh
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prereqs
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: sno-cluster
  source:
    repoURL: "https://github.com/YOUR_ORG/aap-ocp-karaoren.git"  # ← UPDATE
    targetRevision: main
    path: gitops/apps/vault
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: sno-cluster
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    chart: vault
    targetRevision: 0.32.0
    helm:
      valueFiles: []
      values: |
        server:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution: []
          replicas: 1
        injector:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution: []
          replicas: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
