# Wave 8: ExternalSecret resources (sync secrets from Vault → OCP)
# Requires: ClusterSecretStore "vault" is healthy, secrets exist in Vault
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: sno-cluster
  source:
    repoURL: "https://github.com/YOUR_ORG/aap-ocp-karaoren.git"  # ← UPDATE
    targetRevision: main
    path: gitops/secrets/external-secrets
  destination:
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
