apiVersion: v1
kind: Secret
metadata:
  name: alhambra-checker
  namespace: alhambra-checker
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: "<your-twilio-account-sid>"
  TWILIO_AUTH_TOKEN: "<your-twilio-auth-token>"
  TWILIO_FROM_NUMBER: "<your-twilio-phone-number>"
  NOTIFY_PHONE_NUMBER: "<your-mobile-number>"
  SLACK_WEBHOOK_URL: "<from-vault-secret/ocp/slack>"
