# Grafana instance with Google OAuth OIDC and OCP route
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    auth.google:
      enabled: "true"
      allow_sign_up: "true"
      auto_login: "false"
      scopes: openid email profile
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: redhat.com
      role_attribute_path: "email == 'bkaraore@redhat.com' && 'GrafanaAdmin' || 'Viewer'"
      allow_assign_grafana_admin: "true"
    security:
      admin_user: admin
    server:
      root_url: https://grafana-route-grafana.apps.ocp.karaoren.eu
    users:
      auto_assign_org_role: Viewer
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              envFrom:
                - secretRef:
                    name: grafana-google-oauth
  route:
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: grafana
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: grafana
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-token
  namespace: grafana
  annotations:
    kubernetes.io/service-account.name: grafana-sa
type: kubernetes.io/service-account-token
