# ServiceAccount for AAP Execution Environment cluster access
# Used by the cert renewal Job Template to interact with OCP
# (read/write secrets, exec into Vault pod, annotate ExternalSecrets)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-renewal
  namespace: aap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-renewal-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cert-renewal
  namespace: aap
---
# Long-lived token for the ServiceAccount
# Used to create an AAP "OpenShift or Kubernetes API Bearer Token" credential
apiVersion: v1
kind: Secret
metadata:
  name: cert-renewal-token
  namespace: aap
  annotations:
    kubernetes.io/service-account.name: cert-renewal
type: kubernetes.io/service-account-token
